### ISSUE TITLE
fixed: undeclared identifier: 'ProxySocket'

### ISSUE THREAD

**Issue by Techno-Fox** [FedericoCeratto/nim-tor#2]
(Me again) I was working on functions that was use the tor protocol using the identifier ProxySocket. When I tried to compile it said undeclared identifier: 'ProxySocket'. 

So I changed 

```nim
type ProxySocket = ref object of RootObj
  inner*: Socket

```

to 
```nim
type ProxySocket* = ref object of RootObj
  inner*: Socket

```

**Comment by FedericoCeratto** [comment]
(Changed moved to the PR, closing this issue)
