### ISSUE TITLE
Updated tor.nim (patch included)

### ISSUE THREAD

**Issue by Techno-Fox** [FedericoCeratto/nim-tor#3]
I have no Idea how to do a pull request, but I've update the tor.nim to include more like the net module in nim-lang. Also added comments, and made the ProxySocket object public.

Since I don't know how to make a pull request. I'll give you the patch file to patch tor.nim.

patch using command 
"patch tor.nim tor_nim.patch"

[tor_nim.patch.tar.gz](https://github.com/FedericoCeratto/nim-tor/files/5099074/tor_nim.patch.tar.gz)

**Comment by Techno-Fox** [comment]
I'll give you time to update it, but after a while I'll put the updated version on my repositories.

**Comment by Techno-Fox** [comment]
Nevermind, on the patch. I made a pull request.

**Comment by FedericoCeratto** [comment]
(Changed moved to the PR, closing this issue)
